### ISSUE TITLE
Missing install in pypi

### ISSUE THREAD

**Issue by jamiehales** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#13]
Hi,

It seems that the link to the library in pypi for installation with pip is incorrect, and I can only see the display ssd1305 library there. The installation instructions seem to imply that it should be there however?

-Jamie

**Comment by makermelissa** [comment]
I believe it was disabled because Blinka didn't support Displayio. However, I did a lot of work on adding displayio last week. In its current state it still won't support this display, but it shouldn't be far off. I guess that's a long way of saying it's not on PyPI because support was lacking, but hopefully it'll be added soon.

**Comment by jamiehales** [comment]
Great, thank you! I'll continue using the non-displayIO driver for now and wait for compatibility. Thank you very much for the quick response!
